const GET_ALL_POSTS="post:GET_ALL_POSTS";
const DELETE_POST="post:DELETE_POST";
const UPDATE_POST="post:UPDATE_POST";
const ADD_POST="post:ADD_POST";
const GET_THIER_POST="post:GET_THIER_POST";
const BLOCK_POST="post:BLOCK_POST"

module.exports={
    GET_ALL_POSTS,
    DELETE_POST,
    UPDATE_POST,
    ADD_POST,
    GET_THIER_POST,
    BLOCK_POST
}