const GET_ALL_ADVERTISE="advertise:GET_ALL_ADVERTISE";
const DELETE_ADVERTISE="advertise:DELETE_ADVERTISE";
const UPDATE_ADVERTISE="advertise:UPDATE_ADVERTISE";
const ADD_ADVERTISE="advertise:ADD_ADVERTISE";

module.exports={
    GET_ALL_ADVERTISE,
    DELETE_ADVERTISE,
    UPDATE_ADVERTISE,
    ADD_ADVERTISE
}