const { GET_ALL_ADVERTISE ,DELETE_ADVERTISE,UPDATE_ADVERTISE,ADD_ADVERTISE} = require("../../../module/advertise/endpoints");
const { UPDATE_POST,DELETE_POST,GET_ALL_POSTS ,ADD_POST, BLOCK_POST} = require("../../../module/post/endpoints");
const { DELETE_REPORT,GET_ALL_REPORT } = require("../../../module/report/endpoints");
const { ADD_USER, UPDATE_USER, DELETE_ADMIN_USER,GET_ALL_USERS, ADD_ADMIN, BLOCK_USER} = require("../../../module/user/endpoints");

module.exports=[GET_ALL_USERS,ADD_USER,UPDATE_USER, GET_ALL_ADVERTISE , DELETE_ADVERTISE ,UPDATE_ADVERTISE,ADD_ADVERTISE, GET_ALL_POSTS,DELETE_POST,UPDATE_POST,GET_ALL_REPORT,DELETE_REPORT,DELETE_ADMIN_USER,ADD_ADMIN,ADD_POST,BLOCK_POST,BLOCK_USER] 