const GET_ALL_USERS="user:GET_ALL_USERS";
const DELETE_ADMIN_USER="user:DELETE_USER";
const UPDATE_USER="user:UPDATE_USER";
const ADD_USER="user:ADD_USER";
const ADD_ADMIN="user:ADD_ADMIN";
const BLOCK_USER="user:BLOCK_USER";

module.exports={
    GET_ALL_USERS,
    DELETE_ADMIN_USER,
    UPDATE_USER,
    ADD_USER,
    ADD_ADMIN,
    BLOCK_USER

}